QuestionAnswer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='qa/')),
    path('admin/', admin.site.urls, name='admin'),
    path('qa/', include('question_and_answer.urls')),
]

question_and_answer/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from . import views

app_name = 'question_and_answer'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/', views.category, name='category'),
    path('questions/<int:category_id>', views.questions, name='questions'),
    path('questionsOrder1/<int:category_id>/',views.questionsOrder1, name='questionsOrder1'),
    path('questionsOrder2/<int:category_id>/',views.questionsOrder2, name='questionsOrder2'),
    path('questions/detail/<int:id>/', views.detail, name='detail'),
    path('questions/like/<int:id>/<str:type>/', views.like, name='like'),
    path('questions/unlike/<int:id>/<str:type>/', views.unlike, name='unlike'),
    path('ask/', views.ask, name='ask'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('about/',views.about, name='about'),
    path('profile/', views.profile, name='profile'),
    path('myquestions/', views.myquestions, name='myquestions'),
    path('modification/',views.modification, name='modification'),
    path('notice/', views.notice, name='notice'),
]

question_and_answer/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Question
import re

# 此文件是登录及注册的表单, 放在一起便于管理
# 以及还有对输入合法性检验的函数

def email_check(email):
    pattern = re.compile(r"\"?([-a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?")
    return re.match(pattern, email)


class RegistrationForm(forms.Form):

    username = forms.CharField(label='Username', max_length=50,widget=forms.TextInput(attrs={'class':'input'}))
    email = forms.EmailField(label='Email',widget=forms.EmailInput(attrs={'class':'input'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'input'}))
    password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput(attrs={'class':'input'}))
    identity = forms.ChoiceField(label='Identity', choices=[('student','Student'),('teacher', 'Teacher')], required=True, widget=forms.RadioSelect(attrs={'id':'identity', 'class':'select'}))

    # Use clean methods to define custom validation rules

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if len(username) < 2:
            raise forms.ValidationError("Your username must be at least 2 characters long.")
        elif len(username) > 50:
            raise forms.ValidationError("Your username is too long.")
        else:
            filter_result = User.objects.filter(username__exact=username)
            if len(filter_result) > 0:
                raise forms.ValidationError("Your username already exists.")

        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if email_check(email):
            filter_result = User.objects.filter(email__exact=email)
            if len(filter_result) > 0:
                raise forms.ValidationError("Your email already exists.")
        else:
            raise forms.ValidationError("Please enter a valid email.")

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if len(password1) < 6:
            raise forms.ValidationError("Your password is too short.")
        elif len(password1) > 20:
            raise forms.ValidationError("Your password is too long.")

        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Password mismatch. Please enter again.")

        return password2


class LoginForm(forms.Form):

    username = forms.CharField(label='Username', max_length=50, widget=forms.TextInput(attrs={"id":"username","class":"input"}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={"id":"password","class":"input"}))
    # Use clean methods to define custom validation rules

    def clean_username(self):
        username = self.cleaned_data.get('username')

        if email_check(username):
            filter_result = User.objects.filter(email__exact=username)
            if not filter_result:
                raise forms.ValidationError("This email does not exist.")
        else:
            filter_result = User.objects.filter(username__exact=username)
            if not filter_result:
                        raise forms.ValidationError("This username does not exist. Please register first.")

        return username


class AskForm(forms.Form):
    category = forms.ChoiceField(label='请选择问题种类', choices=[(0,'物理'),(1,'数学'),(2,'语言'),(3,'金融')], required=True,
                                 widget=forms.RadioSelect)
    title = forms.CharField(label='请输入问题题目(60字以内):', max_length=60,required=True, widget=forms.TextInput(attrs={"class":"form-control"}))
    question = forms.CharField(label='请输入问题内容(2000字以内):', max_length=2000, required=True,widget=forms.Textarea(attrs={"class":"form-control"}))

    def clean_category(self):
        category = self.cleaned_data.get('category')
        if int(category) < 0 or int(category) > 3:
            raise forms.ValidationError("你选择的模块不存在")
        return category

    def clean_title(self):
        title = self.cleaned_data.get('title')

        if len(title) < 3:
            raise forms.ValidationError("Your title must be at least 3 characters long.")
        elif len(title) > 60:
            raise forms.ValidationError("Your title is too long.")
        else:
            filter_result = Question.objects.filter(question_title__exact=title)
            if len(filter_result) > 0:
                raise forms.ValidationError("Your title already exists.")
        return title

    def clean_question(self):
        question = self.cleaned_data.get('question')

        if len(question) < 3:
            raise forms.ValidationError("Your text must be at least 3 characters long.")
        elif len(question) > 2000:
            raise forms.ValidationError("Your text is too long.")
        else:
            return question

class AnswerForm(forms.Form):
    answer = forms.CharField(label='answer', max_length=2000, widget=forms.Textarea(attrs={'name':"answer", 'class':"form-control",'rows':"10"}))

    def clean_answer(self):
        answer = self.cleaned_data.get('answer')

        if len(answer) < 3:
            raise forms.ValidationError("Your answer must be at least 3 characters long.")
        elif len(answer) > 2000:
            raise forms.ValidationError("Your answer is too long.")
        else:
            return answer

class ProfileForm(forms.Form):
    name = forms.CharField(max_length = 100, label='名字：')
    picture = forms.ImageField(label='图片：')

question_and_answer/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.utils import timezone
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import RegistrationForm, LoginForm, AskForm, AnswerForm, ProfileForm
from .models import *

def index(request):
    try:
        question_list1 = Question.objects.order_by('-pub_date')[:3]
        question_list2 = Question.objects.order_by('-grade')[:3]
        student_num = len(Student.objects.all())
        teacher_num = len(Teacher.objects.all())
        question_num = len(Question.objects.all())
        answer_num = len(Answer.objects.all())
    except:
        question_list1 = []
        question_list2 =[]
        student_num = 0
        teacher_num = 0
        question_num = 0
        answer_num = 0
    if request.user.is_authenticated:
        username = request.user.username
        is_logged_in = True
    else:
        username = '未登录'
        is_logged_in = False
    context = {
        'username':username,
        'question_list1': question_list1,
        'question_list2': question_list2,
        'student_num': student_num,
        'question_num': question_num,
        'teacher_num': teacher_num,
        'answer_num': answer_num,
        'is_logged_in': is_logged_in,
    }
    return render(request, 'question_and_answer/index.html', context)


def category(request):
    if request.user.is_authenticated:
        username = request.user.username
        is_logged_in = True
    else:
        username = '未登录'
        is_logged_in = False
    try:
        question_list = []
        for i in range(4):
            question_list.append(Question.objects.filter(question_category__number=i).order_by('-grade')[:6])
        context = {
            'username': username,
            'question_list1': question_list[0],
            'question_list2': question_list[1],
            'question_list3': question_list[2],
            'question_list4': question_list[3],
            'is_logged_in': is_logged_in,
        }
    except:
        context = {
            'username': username,
            'question_list1': [],
            'question_list2': [],
            'question_list3': [],
            'question_list4': [],
            'is_logged_in': is_logged_in,
        }
    return render(request, 'question_and_answer/category.html', context)

def questions(request, category_id):
    return HttpResponseRedirect(reverse('question_and_answer:questionsOrder1', args={category_id,}))


def questionsOrder1(request, category_id):
    if request.user.is_authenticated:
        username = request.user.username
        is_logged_in = True
    else:
        username = '未登录'
        is_logged_in = False
    question_list = Question.objects.filter(question_category__number=category_id).order_by('-pub_date')[:20]
    context = {
        'question_list':question_list,
        'category':Category.objects.get(number=category_id),
        'username': username,
        'is_logged_in': is_logged_in,
    }
    return render(request, 'question_and_answer/questionsOrder1.html', context)


def questionsOrder2(request, category_id):
    question_list = Question.objects.filter(question_category__number=category_id).order_by('-grade')[:20]
    context = {
        'question_list':question_list,
        'category':Category.objects.get(number=category_id),
    }
    return render(request, 'question_and_answer/questionsOrder2.html', context)

def detail(request, id):
    '''
    查看问题详细内容
    '''
    if request.method == 'POST':
        answer(request, id)
    form = AnswerForm()
    context = {}
    if request.user.is_authenticated:
        username = request.user.username
        is_logged_in = True


    else:
        username = '未登录'
        is_logged_in = False
    question = get_object_or_404(Question, pk=id)
    context['form'] = form
    context['username'] = username
    context['is_logged_in'] = is_logged_in
    context['question'] = question
    return render(request, 'question_and_answer/question_detail.html', context)

'''
@login_required() 是一个装饰器, 要求必须登录后才能查看, 跳转至登录界面
'''

@login_required(login_url='/qa/login/')
def like(request, id, type):
    if type == 'question':
        question = Question.objects.get(id=id)
        question.good_num += 1
        question.grade = question.grade + 10
        question.save()
        return HttpResponseRedirect(reverse('question_and_answer:detail', args=(id,)))
    else:
        answer = Answer.objects.get(id=id)
        answer.good_num += 1
        answer.save()
        return HttpResponseRedirect(reverse('question_and_answer:detail', args=(answer.question.id,)))

@login_required(login_url='/qa/login/')
def unlike(request, id, type):
    if type == 'question':
        question = Question.objects.get(id=id)
        question.bad_num += 1
        question.grade = question.grade - 7
        question.save()
        return HttpResponseRedirect(reverse('question_and_answer:detail', args=(id,)))
    else:
        answer = Answer.objects.get(id=id)
        answer.bad_num += 1
        answer.save()
        return HttpResponseRedirect(reverse('question_and_answer:detail', args=(answer.question.id,)))


@login_required(login_url='/qa/login/')
def answer(request, id):
    question = get_object_or_404(Question, id=id)
    if request.method == 'POST':
        user_id = request.user.id
        user = User.objects.get(id=user_id)
        if user:
            pass
        else:
            return HttpResponseRedirect(reverse('question_and_answer:detail',  args={id, }))
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer_text = form.cleaned_data['answer']
            answer = Answer(
                user = user,
                question = question,
                answer_text = answer_text,
            )
            answer.save()
            return HttpResponseRedirect(reverse('question_and_answer:detail', args={id, }))
    return HttpResponseRedirect(reverse('question_and_answer:detail', args={id, }) )


@login_required(login_url='/qa/login/')
def ask(request):
    if request.user.is_authenticated:
        username = request.user.username
        is_logged_in = True
    else:
        username = '未登录'
        is_logged_in = False
    context = {
        'username': username,
        'is_logged_in': is_logged_in,
    }
    if request.method == 'POST':
        id = request.user.id
        user = User.objects.get(id=id)
        if user:
            pass
        else:
            return HttpResponseRedirect(reverse('question_and_answer:index'))
        form = AskForm(request.POST)
        if form.is_valid():
            question_category_number = form.cleaned_data['category']
            question_title = form.cleaned_data['title']
            question_text = form.cleaned_data['question']
            question_category = Category.objects.get(number=question_category_number)
            question = Question(
                user=user,
                question_title=question_title,
                question_category=question_category,
                question_text=question_text,
            )
            question.save()
            return render(request, 'question_and_answer/ask2.html', {})
        else:
            context['askMessage'] = "您的输入含有非法字符, 请重试!"
            return
    else:
        form = AskForm()
        context['form'] = form
    return render(request, 'question_and_answer/ask.html', context)

def register(request):
    form1 = LoginForm()
    form2 = RegistrationForm()
    context = {
        'loginForm': form1,
        'registrationForm': form2,
    }
    if request.method == 'POST':
        form2 = RegistrationForm(request.POST)
        if form2.is_valid():
            username = form2.cleaned_data['username']
            email = form2.cleaned_data['email']
            password = form2.cleaned_data['password2']
            identity = form2.identity
            user = User.objects.create_user(username=username, email=email, password=password)
            if identity == 'student':
                student = Student(user=user)
                student.save()
            else:
                teacher = Teacher(user=user)
                teacher.save()
            context['loginMessage'] = "注册成功! 请登录"
            return render(request, 'question_and_answer/login_register.html', context)
        else:
            context['registerMessage'] = "表单无效, 请重新提交"
            return render(request, 'question_and_answer/login_register.html', context)
    else:
        return render(request, 'question_and_answer/login_register.html',context)


def login(request):
    form1 = LoginForm()
    form2 = RegistrationForm()
    context = {
        'loginForm': form1,
        'registrationForm': form2,
    }
    if request.method == 'POST':
        form1 = LoginForm(request.POST)
        if form1.is_valid():
            username = form1.cleaned_data['username']
            password = form1.cleaned_data['password']

            user = auth.authenticate(username=username, password=password)
            if user is not None and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('question_and_answer:index'))
            else:
                context['loginMessage'] = "密码或用户名错误, 请重试"
                return render(request, 'question_and_answer/login_register.html', context)
        else:
            context['loginMessage'] = "密码或用户名错误, 请重试"
            return render(request, 'question_and_answer/login_register.html', context)
    else:
        return render(request, 'question_and_answer/login_register.html', context)


@login_required(login_url='qa/login/')
def logout(request):
    auth.logout(request)
    request.session.flush()
    return HttpResponseRedirect(reverse('question_and_answer:index'))

question_and_answer/templates/question_and_answer/about.html
<!DOCTYPE HTML>
<html>
	<head>
    {% load static %}
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>about</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />

	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400" rel="stylesheet">
	
	<!-- Animate.css' %} -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style-question.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<body>
		
	<div class="fh5co-loader"></div>
	
    <div id="page">
	<nav class="fh5co-nav" role="navigation">

		<div class="top-menu">
			<div class="container">
				<div class="row">
					<div class="col-xs-2">
						<div id="fh5co-logo"><a href="{% url 'question_and_answer:index'%}"><i class="icon-study"></i>Educ<span>.</span></a></div>
					</div>
					<div class="col-xs-10 text-right menu-1">
						<ul>
							<li><a href="{% url 'question_and_answer:index'%}">Home</a></li>
							<li><a href="{% url 'question_and_answer:category'%}">Question</a></li>
							<li><a href="{% url 'question_and_answer:ask'%}">Ask</a></li>
							<li class="active"><a href="#">About</a></li>
                            {% if is_logged_in %}
                                <li class="has-dropdown">
                                    <a href="{% url 'question_and_answer:profile' %}">{{ username }}</a>
                                    <ul class="dropdown">
                                        <li><a href="{% url 'question_and_answer:profile' %}">个人信息</a></li>
                                        <li><a href="{% url 'question_and_answer:myquestions' %}">我的问题</a></li>
                                        <li><a href="{% url 'question_and_answer:notice' %}">通知与私信</a></li>
                                        <li><a href="{% url 'question_and_answer:logout' %}">退出登录</a></li>
                                    </ul>
                                </li>
                            {% else %}
                                <li><a href="{% url 'question_and_answer:register' %}">Register</a></li>
                                <li class="btn-cta"><a href="{% url 'question_and_answer:login' %}"><span>Login</span></a></li>
                            {% endif %}
                        </ul>
					</div>
				</div>
				
			</div>
		</div>
	</nav>
	
	<aside id="fh5co-hero">
		<div class="flexslider">
			<ul class="slides">
		   	<li style="background-image: url({% static 'images/img_bg_4.jpg' %});">
		   		<div class="overlay-gradient"></div>
		   		<div class="container">
		   			<div class="row">
			   			<div class="col-md-8 col-md-offset-2 text-center slider-text">
			   				<div class="slider-text-inner">
			   					<h1 class="heading-section">About Us</h1>
									<h2>The Website Made by </h2>
			   				</div>
			   			</div>
			   		</div>
		   		</div>
		   	</li>
		  	</ul>
	  	</div>
	</aside>

	<div id="fh5co-about">
		<div class="container">
			<div class="col-md-6 animate-box">
				<span>About Us</span>
				<h2>Welcome to QUESTION ASK&ANSWER Website</h2>
				<p>........................................................................................................................</p>
				<p>................................................................................................................................</p>
				<p>............................................................................................................................</p>
			</div>
			<div class="col-md-6">
				<img class="img-responsive" src="{% static 'images/img_bg_3.jpg' %}" alt="Free HTML5 Bootstrap Template">
			</div>
		</div>
	</div>
	<footer id="fh5co-footer" role="contentinfo" style="background-image: url({% static 'images/img_bg_4.jpg' %});">
		<div class="overlay"></div>
		<div class="container">
			<div class="row row-pb-md">
				<div class="col-md-3 fh5co-widget">
					<h3>About Us</h3>
					<p>我们致力于建设出优秀的问题交流平台，不仅是为了解惑，更是为了提问，达成师生间的双向互动。</p>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1 fh5co-widget">
					<h3>Learning</h3>
					<ul class="fh5co-footer-links">
						<li><a href="{% url 'question_and_answer:category'%}">Question</a></li>
						<li><a href="{% url 'question_and_answer:ask'%}">Ask</a></li>
						<li><a href="{% url 'question_and_answer:about' %}">About</a></li>
						<li><a href="{% url 'question_and_answer:register' %}">Register</a></li>
					</ul>
				</div>

				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1 fh5co-widget">
					<h3>Team</h3>
					<ul class="fh5co-footer-links">
						<li><a>Zhang Xiheng</a></li>
						<li><a>Huo Yufei</a></li>
						<li><a>Le Youming</a></li>
						<li><a>Wei Shangqing</a></li>
						<li><a>Yang Lina</a></li>
						<li><a>Yuan Xin</a></li>
						<li><a>Zheng Jiaxing</a></li>
						<li><a>Zhou Zhimo</a></li>
					</ul>
				</div>

				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1 fh5co-widget">
					<h3>Thanks For</h3>
					<ul class="fh5co-footer-links">
						<li><a>Doctor Ma Yinghua</a></li>
						<li><a>Teaching Assistants</a></li>
					</ul>
				</div>
			</div>

		</div>
	</footer>
</div>
	


	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	
	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Stellar Parallax -->
	<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
	<!-- Carousel -->
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
	<!-- countTo -->
	<script src="{% static 'js/jquery.countTo.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/magnific-popup-options.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

question_and_answer/templates/question_and_answer/login_register.html
<!doctype html>
<html lang="zh">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Or Register</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/jigsaw.css' %}">
    <style>

        #msg {
            width: 100%;
            line-height: 40px;
            font-size: 14px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="jq22-container" style="padding-top:100px">
    <div class="login-wrap">
        <div class="login-html">
            <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">登录</label>
            <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">注册</label>
            <div class="login-form">

                <form action="{% url 'question_and_answer:login' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <div class="sign-in-htm">
                        {% for field in loginForm %}
                            <div class="group">
                                 <label class="label">{{ field.errors }}</label>
                                <label class="label"> {{ field.label_tag }}</label>{{ field }}
                            </div>
                        {% endfor %}
                        <div class="group">
                            <div class="container">
                                <div id="captcha" style="position: relative" data-type="password"></div>
                                <div id="msg"></div>
                            </div>
                        </div>
                        {{ loginMessage }}

                        <div class="hr"></div>
                        <div class="group">
                            <input name="login" type="submit" class="button" value="登录" disabled="disabled">
                        </div>
						<div class="foot-lnk">
							<a href="/admin/">管理员登录</a>
						</div>
                    </div>
                </form>
                <form action="{% url 'question_and_answer:register' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <div class="sign-up-htm">

                        {% for field in registrationForm %}
                            <div class="group">
                                <label class="label">{{ field.errors }}</label>
                                <label class="label"> {{ field.label_tag }}</label>{{ field }}
                            </div>
                        {% endfor %}
                        {{ registerMessage }}
                        <div class="group">
                            <input type="submit" class="button" value="注册">
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
</div>
<script src="{% static 'js/jigsaw.js' %}"></script>
<script>
    var flag = false;
    jigsaw.init(document.getElementById('captcha'), function () {
        flag = true;
        $("input[name=login]").removeAttr("disabled");
        document.getElementById('msg').innerHTML = '验证成功！'
    })
</script>
<!-- jQuery -->
<script src="{% static 'js/jquery.min.js' %}"></script>

</body>
</html>